### ISSUE TITLE
验证失败

### ISSUE THREAD

**Issue by zhaotianen** [wycm/selenium-geetest-crack#1]
Connected to the target VM, address: '127.0.0.1:53849', transport: 'socket'
Starting ChromeDriver 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41) on port 40188
Only local connections are allowed.
九月 01, 2017 2:14:02 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
九月 01, 2017 2:14:04 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: OSS
https://static.geetest.com/pictures/gt/579066de6/579066de6.jpg
https://static.geetest.com/pictures/gt/579066de6/bg/28d706c82.jpg
应平移距离：157
(416, 891)
-1--1
(418, 891)
157--1
(614, 891)
验证失败:---拖动滑块将悬浮图像正确拼合
https://static.geetest.com/pictures/gt/579066de6/579066de6.jpg
https://static.geetest.com/pictures/gt/579066de6/bg/28d706c82.jpg
应平移距离：157
(416, 891)
-3--1
(418, 891)
157--1
(563, 891)
Exception in thread "main" org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=59.0.3071.109)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 13 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'PC-20170328ESTJ', ip: '192.168.1.128', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41), userDataDir=C:\Users\Mypc\AppData\Local\Temp\scoped_dir4260_30398}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.109, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 14ab79a69ca4b16987212fdf8d92c1ca
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:274)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:158)
	at com.github.wycm.GeettestCrawler.invoke(GeettestCrawler.java:78)
	at com.github.wycm.GeettestCrawler.main(GeettestCrawler.java:52)
Disconnected from the target VM, address: '127.0.0.1:53849', transport: 'socket'

Process finished with exit code 1

**Comment by wycm** [comment]
验证失败是有一定可能出现的。是一直失败吗
